version: '3.8'
services:
  db:
    image: postgres:14.7
    networks:
      - servicedesk-network
    restart: always
    ports:
      - "0.0.0.0:${DKDB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_HOST}
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
  servicedeskapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: appservicedesk:1.0.0
    networks:
      - servicedesk-network
    container_name: SeriviceDeskApp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./images:/var/www/ServiceDesk/images
    environment:
      PORT: ${PORT}
      SECRETORPRIVATEKEY: ${SECRETORPRIVATEKEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_DIAL: ${DB_DIAL}
volumes:
  images:
  postgresdb:
networks:
  servicedesk-network:
    driver: bridge